UUID_LENGTH = 36
BUSINESS_CODE_LENGTH = 16
COUPON_CODE_LENGTH = 16
USER_QR_CODE_LENGTH = 16
MAX_STRING_LENGTH = 128
MAX_PHONE_LENGTH = 18
MAX_PASSWORD_LENGTH = 128
MAX_TITLE_NAME = 20
MAX_NEWS_CONTENT_LENGTH = 512

BUSINESS_CODE_LEN = 16
COUPON_CODE_LEN = 16
USER_QR_CODE_LEN = 16
