"""businenss code pk

Revision ID: 2de15655c98a
Revises: 2a6da3681dd5
Create Date: 2024-10-06 20:12:30.778182+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de15655c98a'
down_revision: Union[str, None] = '2a6da3681dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_code', table_name='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_business_code', 'business', ['code'], unique=False)
    # ### end Alembic commands ###
