"""Add revoked to OTP

Revision ID: 2ed98cbbe346
Revises: eeaf4d9861c6
Create Date: 2024-09-28 14:34:20.249620+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed98cbbe346'
down_revision: Union[str, None] = 'eeaf4d9861c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'revoked')
    # ### end Alembic commands ###
