"""add qr code to client

Revision ID: 4531538a59f5
Revises: c55ff6902daa
Create Date: 2024-10-11 22:39:23.783839+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4531538a59f5'
down_revision: Union[str, None] = 'c55ff6902daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('qr_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'qr_code')
    # ### end Alembic commands ###
