"""add business to tokens

Revision ID: 56a155586ca7
Revises: f63d02aea3ae
Create Date: 2024-10-01 17:06:41.181637+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a155586ca7'
down_revision: Union[str, None] = 'f63d02aea3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('business', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('business', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'business')
    op.drop_column('access_tokens', 'business')
    # ### end Alembic commands ###
