"""add a fucking fk

Revision ID: 6a13a57480b8
Revises: db14eaa10f36
Create Date: 2024-10-08 17:40:29.658078+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a13a57480b8'
down_revision: Union[str, None] = 'db14eaa10f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'access_tokens', 'business', ['business_code'], ['code'])
    op.alter_column('business', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'business', 'users', ['owner_id'], ['id'])
    op.add_column('clients', sa.Column('business_code', sa.String(), nullable=False))
    op.alter_column('clients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'clients', 'business', ['business_code'], ['code'])
    op.drop_column('clients', 'business')
    op.create_foreign_key(None, 'otps', 'business', ['business'], ['code'])
    op.add_column('refresh_tokens', sa.Column('business_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'refresh_tokens', 'business', ['business_code'], ['code'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('business', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'business_code')
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.add_column('clients', sa.Column('business', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('clients', 'business_code')
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.alter_column('business', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'access_tokens', type_='foreignkey')
    # ### end Alembic commands ###
