"""mixins

Revision ID: 8c8cbdc57b79
Revises: f93e801f3242
Create Date: 2024-10-06 11:36:47.042970+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c8cbdc57b79'
down_revision: Union[str, None] = 'f93e801f3242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('business', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('business_client', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('business_client', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('business_client', 'registration_date')
    op.add_column('otps', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('otps', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('otps', 'updated_at')
    op.drop_column('otps', 'created_at')
    op.add_column('business_client', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('business_client', 'updated_at')
    op.drop_column('business_client', 'created_at')
    op.drop_column('business', 'updated_at')
    op.drop_column('business', 'created_at')
    # ### end Alembic commands ###
