"""fix

Revision ID: a28d3fab5d80
Revises: 1c01042f2c37
Create Date: 2024-10-21 17:09:31.371119+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a28d3fab5d80"
down_revision: Union[str, None] = "1c01042f2c37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_schedule_infos", sa.Column("is_opened", sa.Boolean(), nullable=True)
    )
    op.drop_column("day_schedule_infos", "is_day_off")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_schedule_infos",
        sa.Column("is_day_off", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("day_schedule_infos", "is_opened")
    # ### end Alembic commands ###
