"""update business and client models

Revision ID: b7b059898b76
Revises: e7efa94b2dd8
Create Date: 2024-10-11 13:16:03.024288+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b059898b76'
down_revision: Union[str, None] = 'e7efa94b2dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('picture', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bonuses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'bonuses')
    op.drop_column('clients', 'picture')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    op.drop_column('business', 'picture')
    # ### end Alembic commands ###
