"""add owner id

Revision ID: f93e801f3242
Revises: f6ac322cb251
Create Date: 2024-10-06 00:08:39.568346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93e801f3242'
down_revision: Union[str, None] = 'f6ac322cb251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_column('business', 'owner_id')
    # ### end Alembic commands ###
